export const background = '#FFFFFF'

export const black = '#292929'
export const white = '#FFFFFF'
export const grey = '#BCBCBC'
export const lightGrey = '#F5F8F9'
export const red = '#F54D3F'
export const yellow = '#facd02'
export const blue = '#2980B9'
export const backroundPrimary = '#F5F5F5'
export const backroundSecondary = '#F5F8F9'
export const orange = 'orange'
export const none = 'none'
export const main = '#2BB0AD'
export const textPrimary = '#061A1A'
